CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	genre_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Performer (
	id SERIAL PRIMARY KEY,
	performer_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	album_name VARCHAR(50) NOT NULL,
	release_year INTEGER check (1979 < release_year < 2000) NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	collection_name VARCHAR(50) NOT NULL,
	release_year INTEGER check (1979 < release_year < 2000) NOT NULL
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	track_name VARCHAR(50) NOT NULL,
	duration INTEGER NOT NULL,
	AlbumID INTEGER NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS PerformerGenre (
	GenreID INTEGER NOT NULL REFERENCES Genre(id),
	PerformerID INTEGER NOT NULL REFERENCES Performer(id),
	CONSTRAINT pk1 PRIMARY KEY (GenreID, PerformerID)
);

CREATE TABLE IF NOT EXISTS AlbumPerformer (
	PerformerID INTEGER NOT NULL REFERENCES Performer(id),
	AlbumID INTEGER NOT NULL REFERENCES Album(id),
	CONSTRAINT pk2 PRIMARY KEY (PerformerID, AlbumID)
);

CREATE TABLE IF NOT EXISTS CollectionTrack (
	TrackID INTEGER NOT NULL REFERENCES Track(id),
	CollectionID INTEGER NOT NULL REFERENCES Collection(id),
	CONSTRAINT pk3 PRIMARY KEY (TrackID, CollectionID)
);